package scoring.core;

import scoring.core.dto.BonusItem;
import scoring.core.dto.CandidateInfo;
import scoring.core.dto.CandidateStatus;
import scoring.core.dto.ScoreItem;
import scoring.core.dto.SystemStats;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * H2 嵌入式文件数据库的 DAO（包内私有实现，不构成对外 API）。
 *
 * <p>数据库：{@code jdbc:h2:file:<path>}，单文件、本地存储，文件位置由调用方（CLI/GUI）
 * 通过 JDBC URL 指定。全部表结构见 docs/接口文档.md「表结构」一节。
 */
final class Store implements AutoCloseable {

    private final Connection conn;

    Store(String jdbcUrl) {
        try {
            conn = DriverManager.getConnection(jdbcUrl, "sa", "");
            initSchema();
        } catch (SQLException e) {
            throw new IllegalStateException("无法打开数据库（" + jdbcUrl + "）：" + e.getMessage(), e);
        }
    }

    private void initSchema() throws SQLException {
        String[] ddl = {
                "CREATE TABLE IF NOT EXISTS candidate ("
                        + " student_no VARCHAR(10) PRIMARY KEY,"
                        + " name VARCHAR(64) NOT NULL,"
                        + " status VARCHAR(16) NOT NULL DEFAULT 'PENDING',"
                        + " finished_at TIMESTAMP,"
                        + " imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
                        + " updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
                "CREATE TABLE IF NOT EXISTS score ("
                        + " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " student_no VARCHAR(10) NOT NULL,"
                        + " points DECIMAL(6,2) NOT NULL CHECK (points >= 0 AND points <= 100),"
                        + " created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
                "CREATE INDEX IF NOT EXISTS idx_score_no ON score(student_no)",
                "CREATE TABLE IF NOT EXISTS bonus ("
                        + " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " student_no VARCHAR(10) NOT NULL,"
                        + " amount DECIMAL(6,2) NOT NULL CHECK (amount >= 0 AND amount <= 100),"
                        + " reason VARCHAR(200) NOT NULL,"
                        + " created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
                "CREATE INDEX IF NOT EXISTS idx_bonus_no ON bonus(student_no)",
                "CREATE TABLE IF NOT EXISTS op_log ("
                        + " seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " student_no VARCHAR(10) NOT NULL,"
                        + " op_type VARCHAR(12) NOT NULL,"
                        + " ref_id BIGINT NOT NULL,"
                        + " points DECIMAL(6,2),"
                        + " reason VARCHAR(200),"
                        + " occurred_at TIMESTAMP,"
                        + " created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)"
        };
        try (Statement st = conn.createStatement()) {
            for (String sql : ddl) {
                try {
                    st.execute(sql);
                } catch (SQLException e) {
                    // 幂等兜底：不同 H2 版本对 CREATE INDEX IF NOT EXISTS 支持不一致，
                    // 对象已存在（H2 错误码 42111）时视为正常，其余异常照常抛出。
                    if (e.getErrorCode() == 42111
                            || (e.getMessage() != null && e.getMessage().contains("already exists"))) {
                        continue;
                    }
                    throw e;
                }
            }
        }
    }

    // ------------------------------------------------------------------ 候选人

    /** 幂等 upsert：学号已存在则更新姓名并刷新 updated_at，返回是否为新插入。 */
    boolean upsertCandidate(String studentNo, String name) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE candidate SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE student_no = ?")) {
            ps.setString(1, name);
            ps.setString(2, studentNo);
            if (ps.executeUpdate() > 0) {
                return false;
            }
        }
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO candidate (student_no, name) VALUES (?, ?)")) {
            ps.setString(1, studentNo);
            ps.setString(2, name);
            ps.executeUpdate();
            return true;
        }
    }

    Optional<CandidateInfo> findCandidate(String studentNo) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate WHERE student_no = ?")) {
            ps.setString(1, studentNo);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(rowToCandidate(rs)) : Optional.empty();
            }
        }
    }

    List<CandidateInfo> listCandidates() throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate ORDER BY student_no");
             ResultSet rs = ps.executeQuery()) {
            List<CandidateInfo> out = new ArrayList<>();
            while (rs.next()) {
                out.add(rowToCandidate(rs));
            }
            return out;
        }
    }

    List<CandidateInfo> listByStatus(CandidateStatus status) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate WHERE status = ? ORDER BY student_no")) {
            ps.setString(1, status.name());
            try (ResultSet rs = ps.executeQuery()) {
                List<CandidateInfo> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(rowToCandidate(rs));
                }
                return out;
            }
        }
    }

    Optional<CandidateInfo> findInterviewing() throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate"
                        + " WHERE status = 'INTERVIEWING' ORDER BY student_no LIMIT 1")) {
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(rowToCandidate(rs)) : Optional.empty();
            }
        }
    }

    void updateStatus(String studentNo, CandidateStatus status, LocalDateTime finishedAt) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE candidate SET status = ?, finished_at = ? WHERE student_no = ?")) {
            ps.setString(1, status.name());
            ps.setTimestamp(2, finishedAt == null ? null : Timestamp.valueOf(finishedAt));
            ps.setString(3, studentNo);
            ps.executeUpdate();
        }
    }

    List<CandidateInfo> searchByName(String keyword, int limit) throws SQLException {
        String like = "%" + escapeLike(keyword) + "%";
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate"
                        + " WHERE name LIKE ? ESCAPE '\\' ORDER BY student_no LIMIT " + limit)) {
            ps.setString(1, like);
            try (ResultSet rs = ps.executeQuery()) {
                List<CandidateInfo> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(rowToCandidate(rs));
                }
                return out;
            }
        }
    }

    List<CandidateInfo> searchByNoPrefix(String prefix, int limit) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate"
                        + " WHERE student_no LIKE ? ORDER BY student_no LIMIT " + limit)) {
            ps.setString(1, prefix + "%");
            try (ResultSet rs = ps.executeQuery()) {
                List<CandidateInfo> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(rowToCandidate(rs));
                }
                return out;
            }
        }
    }

    SystemStats stats() throws SQLException {
        Map<CandidateStatus, Integer> byStatus = new EnumMap<>(CandidateStatus.class);
        int total = 0;
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT status, COUNT(*) AS c FROM candidate GROUP BY status");
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                CandidateStatus s = CandidateStatus.fromDb(rs.getString("status"));
                byStatus.put(s, rs.getInt("c"));
                total += rs.getInt("c");
            }
        }
        return new SystemStats(
                total,
                byStatus.getOrDefault(CandidateStatus.PENDING, 0),
                byStatus.getOrDefault(CandidateStatus.INTERVIEWING, 0),
                byStatus.getOrDefault(CandidateStatus.FINISHED, 0),
                countRows("score"),
                countRows("bonus"));
    }

    // ------------------------------------------------------------------ 普通评分

    ScoreItem insertScore(String studentNo, BigDecimal value, LocalDateTime at) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO score (student_no, points, created_at) VALUES (?, ?, ?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, studentNo);
            ps.setBigDecimal(2, value);
            ps.setTimestamp(3, Timestamp.valueOf(at));
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new ScoreItem(keys.getLong(1), studentNo, value, at);
            }
        }
    }

    List<ScoreItem> listScores(String studentNo) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT id, student_no, points, created_at FROM score WHERE student_no = ? ORDER BY id")) {
            ps.setString(1, studentNo);
            try (ResultSet rs = ps.executeQuery()) {
                List<ScoreItem> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(new ScoreItem(rs.getLong("id"), rs.getString("student_no"),
                            rs.getBigDecimal("points"), rs.getTimestamp("created_at").toLocalDateTime()));
                }
                return out;
            }
        }
    }

    Optional<ScoreItem> findScoreByIdAndNo(String studentNo, long id) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT id, student_no, points, created_at FROM score WHERE student_no = ? AND id = ?")) {
            ps.setString(1, studentNo);
            ps.setLong(2, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    return Optional.empty();
                }
                return Optional.of(new ScoreItem(id, studentNo, rs.getBigDecimal("points"),
                        rs.getTimestamp("created_at").toLocalDateTime()));
            }
        }
    }

    Optional<ScoreItem> lastScore(String studentNo) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT id, student_no, points, created_at FROM score WHERE student_no = ?"
                        + " ORDER BY id DESC LIMIT 1")) {
            ps.setString(1, studentNo);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    return Optional.empty();
                }
                return Optional.of(new ScoreItem(rs.getLong("id"), studentNo,
                        rs.getBigDecimal("points"), rs.getTimestamp("created_at").toLocalDateTime()));
            }
        }
    }

    void deleteScoreByIdAndNo(String studentNo, long id) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "DELETE FROM score WHERE student_no = ? AND id = ?")) {
            ps.setString(1, studentNo);
            ps.setLong(2, id);
            ps.executeUpdate();
        }
    }

    void restoreScore(long id, String studentNo, BigDecimal value, LocalDateTime at) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO score (id, student_no, points, created_at) VALUES (?, ?, ?, ?)")) {
            ps.setLong(1, id);
            ps.setString(2, studentNo);
            ps.setBigDecimal(3, value);
            ps.setTimestamp(4, Timestamp.valueOf(at));
            ps.executeUpdate();
        }
    }

    // ------------------------------------------------------------------ 附加分

    BonusItem insertBonus(String studentNo, BigDecimal amount, String reason, LocalDateTime at) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO bonus (student_no, amount, reason, created_at) VALUES (?, ?, ?, ?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, studentNo);
            ps.setBigDecimal(2, amount);
            ps.setString(3, reason);
            ps.setTimestamp(4, Timestamp.valueOf(at));
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new BonusItem(keys.getLong(1), studentNo, amount, reason, at);
            }
        }
    }

    List<BonusItem> listBonuses(String studentNo) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT id, student_no, amount, reason, created_at FROM bonus WHERE student_no = ? ORDER BY id")) {
            ps.setString(1, studentNo);
            try (ResultSet rs = ps.executeQuery()) {
                List<BonusItem> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(new BonusItem(rs.getLong("id"), rs.getString("student_no"),
                            rs.getBigDecimal("amount"), rs.getString("reason"),
                            rs.getTimestamp("created_at").toLocalDateTime()));
                }
                return out;
            }
        }
    }

    void deleteBonusByIdAndNo(String studentNo, long id) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "DELETE FROM bonus WHERE student_no = ? AND id = ?")) {
            ps.setString(1, studentNo);
            ps.setLong(2, id);
            ps.executeUpdate();
        }
    }

    // ------------------------------------------------------------------ 操作日志（撤销）

    /** occurredAt 是「被操作行自身的时间快照」，撤销删除评分时用它还原原录入时间。 */
    void insertOpLog(String studentNo, String opType, long refId,
                     BigDecimal value, String reason, LocalDateTime occurredAt) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO op_log (student_no, op_type, ref_id, points, reason, occurred_at)"
                        + " VALUES (?, ?, ?, ?, ?, ?)")) {
            ps.setString(1, studentNo);
            ps.setString(2, opType);
            ps.setLong(3, refId);
            ps.setBigDecimal(4, value);
            ps.setString(5, reason);
            ps.setTimestamp(6, occurredAt == null ? null : Timestamp.valueOf(occurredAt));
            ps.executeUpdate();
        }
    }

    void deleteOpLogBySeq(long seq) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement("DELETE FROM op_log WHERE seq = ?")) {
            ps.setLong(1, seq);
            ps.executeUpdate();
        }
    }

    Optional<LogRow> lastOpLog() throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT o.seq, o.student_no, o.op_type, o.ref_id, o.points, o.reason, o.occurred_at, o.created_at,"
                        + " c.name FROM op_log o JOIN candidate c ON c.student_no = o.student_no"
                        + " ORDER BY o.seq DESC LIMIT 1")) {
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    return Optional.empty();
                }
                Timestamp occurred = rs.getTimestamp("occurred_at");
                return Optional.of(new LogRow(
                        rs.getLong("seq"),
                        rs.getString("student_no"),
                        rs.getString("name"),
                        rs.getString("op_type"),
                        rs.getLong("ref_id"),
                        rs.getBigDecimal("points"),
                        rs.getString("reason"),
                        occurred == null ? null : occurred.toLocalDateTime(),
                        rs.getTimestamp("created_at").toLocalDateTime()));
            }
        }
    }

    // ------------------------------------------------------------------ 重置

    /** 初始化：事务内清空全部评分/附加分/操作日志，候选人回到未面试（名单保留）。 */
    void resetAll() throws SQLException {
        boolean oldAuto = conn.getAutoCommit();
        conn.setAutoCommit(false);
        try {
            try (Statement st = conn.createStatement()) {
                st.executeUpdate("DELETE FROM op_log");
                st.executeUpdate("DELETE FROM score");
                st.executeUpdate("DELETE FROM bonus");
                st.executeUpdate("UPDATE candidate SET status = 'PENDING', finished_at = NULL");
            }
            conn.commit();
        } catch (SQLException e) {
            conn.rollback();
            throw e;
        } finally {
            conn.setAutoCommit(oldAuto);
        }
    }

    // ------------------------------------------------------------------ 事务

    /** 在事务中执行动作；成功 commit，异常（SQL/运行时）rollback 后原样抛出。 */
    <T> T tx(TxAction<T> action) throws SQLException {
        boolean oldAuto = conn.getAutoCommit();
        conn.setAutoCommit(false);
        try {
            T result = action.run();
            conn.commit();
            return result;
        } catch (SQLException | RuntimeException e) {
            try {
                conn.rollback();
            } catch (SQLException ignored) {
                // 回滚失败无补救路径，保持原始异常
            }
            throw e;
        } finally {
            conn.setAutoCommit(oldAuto);
        }
    }

    @FunctionalInterface
    interface TxAction<T> {
        T run() throws SQLException;
    }

    // ------------------------------------------------------------------ 杂项

    private int countRows(String table) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement("SELECT COUNT(*) FROM " + table);
             ResultSet rs = ps.executeQuery()) {
            rs.next();
            return rs.getInt(1);
        }
    }

    private static CandidateInfo rowToCandidate(ResultSet rs) throws SQLException {
        Timestamp finished = rs.getTimestamp("finished_at");
        return new CandidateInfo(
                rs.getString("student_no"),
                rs.getString("name"),
                CandidateStatus.fromDb(rs.getString("status")),
                finished == null ? null : finished.toLocalDateTime());
    }

    private static String escapeLike(String s) {
        return s.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_");
    }

    @Override
    public void close() {
        try {
            conn.close();
        } catch (SQLException ignored) {
            // 关闭阶段异常无可控处理点；core 层不允许任何控制台输出
        }
    }

    /** op_log 表原始行（含候选人姓名冗余）。 */
    record LogRow(long seq, String studentNo, String studentName, String opType, long refId,
                  BigDecimal value, String reason, LocalDateTime occurredAt, LocalDateTime time) {
    }
}
