package scoring.core;

import scoring.core.dto.BonusItem;
import scoring.core.dto.CandidateInfo;
import scoring.core.dto.CandidateStatus;
import scoring.core.dto.ScoreItem;
import scoring.core.dto.SystemStats;

import java.io.File;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * H2 嵌入式文件数据库的 DAO（包内私有实现，不构成对外 API）。
 *
 * <p>二期 schema：score 为四维列 r/t/s/f（各 0~25）；op_log 保存评分四维快照(r/t/s/f)与
 * 附加分快照(amount/reason)；bonus 单笔 ≤10（新库由 CHECK 强制，旧库迁移后由服务端强校验）。
 *
 * <p>旧库自动迁移：检测到一期 score.points 标量格式时，把 score/op_log 改名归档为
 * score_legacy_v1 / op_log_legacy_v1（旧评分不换算进四维），然后建新表；候选人/附加分保留。
 */
final class Store implements AutoCloseable {

    private final String jdbcUrl;
    private Connection conn;
    private String migrationNotice;

    Store(String jdbcUrl) {
        this.jdbcUrl = jdbcUrl;
        try {
            conn = DriverManager.getConnection(jdbcUrl, "sa", "");
            initSchema();
        } catch (SQLException e) {
            throw new IllegalStateException("无法打开数据库（" + jdbcUrl + "）：" + e.getMessage(), e);
        }
    }

    /** 本次打开是否发生过旧库自动迁移；无则返回 null（GUI/CLI 据此展示提示）。 */
    String migrationNotice() {
        return migrationNotice;
    }

    // ------------------------------------------------------------------ 建表与迁移

    private void initSchema() throws SQLException {
        if (tableExists("candidate") && scoreIsLegacy()) {
            migrateLegacyV1();
        }
        String[] ddl = {
                "CREATE TABLE IF NOT EXISTS candidate ("
                        + " student_no VARCHAR(10) PRIMARY KEY,"
                        + " name VARCHAR(64) NOT NULL,"
                        + " status VARCHAR(16) NOT NULL DEFAULT 'PENDING',"
                        + " finished_at TIMESTAMP,"
                        + " imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
                        + " updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
                "CREATE TABLE IF NOT EXISTS score ("
                        + " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " student_no VARCHAR(10) NOT NULL,"
                        + " r DECIMAL(6,2) NOT NULL CHECK (r >= 0 AND r <= 25),"
                        + " t DECIMAL(6,2) NOT NULL CHECK (t >= 0 AND t <= 25),"
                        + " s DECIMAL(6,2) NOT NULL CHECK (s >= 0 AND s <= 25),"
                        + " f DECIMAL(6,2) NOT NULL CHECK (f >= 0 AND f <= 25),"
                        + " created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
                "CREATE INDEX IF NOT EXISTS idx_score_no ON score(student_no)",
                "CREATE TABLE IF NOT EXISTS bonus ("
                        + " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " student_no VARCHAR(10) NOT NULL,"
                        + " amount DECIMAL(6,2) NOT NULL CHECK (amount >= 0 AND amount <= 10),"
                        + " reason VARCHAR(200) NOT NULL,"
                        + " created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)",
                "CREATE INDEX IF NOT EXISTS idx_bonus_no ON bonus(student_no)",
                "CREATE TABLE IF NOT EXISTS op_log ("
                        + " seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " student_no VARCHAR(10) NOT NULL,"
                        + " op_type VARCHAR(12) NOT NULL,"
                        + " ref_id BIGINT NOT NULL,"
                        + " r DECIMAL(6,2),"
                        + " t DECIMAL(6,2),"
                        + " s DECIMAL(6,2),"
                        + " f DECIMAL(6,2),"
                        + " amount DECIMAL(6,2),"
                        + " reason VARCHAR(200),"
                        + " occurred_at TIMESTAMP,"
                        + " created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)"
        };
        try (Statement st = conn.createStatement()) {
            for (String sql : ddl) {
                try {
                    st.execute(sql);
                } catch (SQLException e) {
                    // 幂等兜底：不同 H2 版本对 CREATE INDEX IF NOT EXISTS 支持不一致，
                    // 对象已存在（H2 错误码 42111）时视为正常，其余异常照常抛出。
                    if (e.getErrorCode() == 42111
                            || (e.getMessage() != null && e.getMessage().contains("already exists"))) {
                        continue;
                    }
                    throw e;
                }
            }
        }
    }

    private boolean tableExists(String table) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = ?")) {
            ps.setString(1, table.toUpperCase());
            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                return rs.getInt(1) > 0;
            }
        }
    }

    /** score 表存在且含一期标量列 points（无四维列 r）→ 判为一期旧库。 */
    private boolean scoreIsLegacy() throws SQLException {
        return tableHasColumn("score", "POINTS") && !tableHasColumn("score", "R");
    }

    private boolean tableHasColumn(String table, String column) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = ? AND COLUMN_NAME = ?")) {
            ps.setString(1, table.toUpperCase());
            ps.setString(2, column.toUpperCase());
            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                return rs.getInt(1) > 0;
            }
        }
    }

    /** 一期库自动迁移：score/op_log 改名归档（旧评分/旧日志不换算、不参与新功能）；候选人保留，但旧“已结束”状态失去评分依据 → 统一重置为未面试。 */
    private void migrateLegacyV1() throws SQLException {
        boolean oldAuto = conn.getAutoCommit();
        conn.setAutoCommit(false);
        try (Statement st = conn.createStatement()) {
            st.executeUpdate("ALTER TABLE score RENAME TO score_legacy_v1");
            if (tableExists("op_log")) {
                st.executeUpdate("ALTER TABLE op_log RENAME TO op_log_legacy_v1");
            }
            // 旧 FINISHED 状态无四维评分支撑，重置为未面试，避免排名等逻辑对“0 条记录的已结束者”误算
            st.executeUpdate("UPDATE candidate SET status = 'PENDING', finished_at = NULL");
            conn.commit();
            migrationNotice = "该库为一期标量评分格式：已自动迁移——旧 score/op_log 归档为 "
                    + "score_legacy_v1 / op_log_legacy_v1，候选人名单保留（其面试状态已重置为未面试）；"
                    + "旧评分不换算进四维（如需留档请另行导出一期 CSV）。";
        } catch (SQLException e) {
            try {
                conn.rollback();
            } catch (SQLException ignored) {
                // 保持原始异常
            }
            throw e;
        } finally {
            conn.setAutoCommit(oldAuto);
        }
    }

    // ------------------------------------------------------------------ 候选人

    /** 幂等 upsert（批量导入用）：学号已存在则更新姓名并刷新 updated_at，返回是否为新插入。 */
    boolean upsertCandidate(String studentNo, String name) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE candidate SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE student_no = ?")) {
            ps.setString(1, name);
            ps.setString(2, studentNo);
            if (ps.executeUpdate() > 0) {
                return false;
            }
        }
        insertCandidate(studentNo, name);
        return true;
    }

    /** 手动新增（调用方需先确认学号不存在，否则 PK 冲突抛 SQLException）。 */
    void insertCandidate(String studentNo, String name) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO candidate (student_no, name) VALUES (?, ?)")) {
            ps.setString(1, studentNo);
            ps.setString(2, name);
            ps.executeUpdate();
        }
    }

    void updateCandidateName(String studentNo, String name) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE candidate SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE student_no = ?")) {
            ps.setString(1, name);
            ps.setString(2, studentNo);
            ps.executeUpdate();
        }
    }

    /** 改学号：事务内级联迁移 score/bonus/op_log 后更新主表（调用方已确认新号不存在、非面试中）。 */
    void moveCandidateStudentNo(String oldNo, String newNo) throws SQLException {
        boolean oldAuto = conn.getAutoCommit();
        conn.setAutoCommit(false);
        try {
            for (String table : new String[]{"score", "bonus", "op_log"}) {
                try (PreparedStatement ps = conn.prepareStatement(
                        "UPDATE " + table + " SET student_no = ? WHERE student_no = ?")) {
                    ps.setString(1, newNo);
                    ps.setString(2, oldNo);
                    ps.executeUpdate();
                }
            }
            try (PreparedStatement ps = conn.prepareStatement(
                    "UPDATE candidate SET student_no = ?, updated_at = CURRENT_TIMESTAMP WHERE student_no = ?")) {
                ps.setString(1, newNo);
                ps.setString(2, oldNo);
                ps.executeUpdate();
            }
            conn.commit();
        } catch (SQLException e) {
            try {
                conn.rollback();
            } catch (SQLException ignored) {
                // 保持原始异常
            }
            throw e;
        } finally {
            conn.setAutoCommit(oldAuto);
        }
    }

    /** 删除候选人：事务内级联删除其评分/附加分/操作日志后再删主表行。 */
    void deleteCandidateCascade(String studentNo) throws SQLException {
        boolean oldAuto = conn.getAutoCommit();
        conn.setAutoCommit(false);
        try {
            for (String table : new String[]{"score", "bonus", "op_log"}) {
                try (PreparedStatement ps = conn.prepareStatement(
                        "DELETE FROM " + table + " WHERE student_no = ?")) {
                    ps.setString(1, studentNo);
                    ps.executeUpdate();
                }
            }
            try (PreparedStatement ps = conn.prepareStatement(
                    "DELETE FROM candidate WHERE student_no = ?")) {
                ps.setString(1, studentNo);
                ps.executeUpdate();
            }
            conn.commit();
        } catch (SQLException e) {
            try {
                conn.rollback();
            } catch (SQLException ignored) {
                // 保持原始异常
            }
            throw e;
        } finally {
            conn.setAutoCommit(oldAuto);
        }
    }

    Optional<CandidateInfo> findCandidate(String studentNo) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate WHERE student_no = ?")) {
            ps.setString(1, studentNo);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(rowToCandidate(rs)) : Optional.empty();
            }
        }
    }

    List<CandidateInfo> listCandidates() throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate ORDER BY student_no");
             ResultSet rs = ps.executeQuery()) {
            List<CandidateInfo> out = new ArrayList<>();
            while (rs.next()) {
                out.add(rowToCandidate(rs));
            }
            return out;
        }
    }

    List<CandidateInfo> listByStatus(CandidateStatus status) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate WHERE status = ? ORDER BY student_no")) {
            ps.setString(1, status.name());
            try (ResultSet rs = ps.executeQuery()) {
                List<CandidateInfo> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(rowToCandidate(rs));
                }
                return out;
            }
        }
    }

    Optional<CandidateInfo> findInterviewing() throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate"
                        + " WHERE status = 'INTERVIEWING' ORDER BY student_no LIMIT 1")) {
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(rowToCandidate(rs)) : Optional.empty();
            }
        }
    }

    void updateStatus(String studentNo, CandidateStatus status, LocalDateTime finishedAt) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE candidate SET status = ?, finished_at = ? WHERE student_no = ?")) {
            ps.setString(1, status.name());
            ps.setTimestamp(2, finishedAt == null ? null : Timestamp.valueOf(finishedAt));
            ps.setString(3, studentNo);
            ps.executeUpdate();
        }
    }

    List<CandidateInfo> searchByName(String keyword, int limit) throws SQLException {
        String like = "%" + escapeLike(keyword) + "%";
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate"
                        + " WHERE name LIKE ? ESCAPE '\\' ORDER BY student_no LIMIT " + limit)) {
            ps.setString(1, like);
            try (ResultSet rs = ps.executeQuery()) {
                List<CandidateInfo> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(rowToCandidate(rs));
                }
                return out;
            }
        }
    }

    List<CandidateInfo> searchByNoPrefix(String prefix, int limit) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT student_no, name, status, finished_at FROM candidate"
                        + " WHERE student_no LIKE ? ORDER BY student_no LIMIT " + limit)) {
            ps.setString(1, prefix + "%");
            try (ResultSet rs = ps.executeQuery()) {
                List<CandidateInfo> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(rowToCandidate(rs));
                }
                return out;
            }
        }
    }

    SystemStats stats() throws SQLException {
        Map<CandidateStatus, Integer> byStatus = new EnumMap<>(CandidateStatus.class);
        int total = 0;
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT status, COUNT(*) AS c FROM candidate GROUP BY status");
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                CandidateStatus s = CandidateStatus.fromDb(rs.getString("status"));
                byStatus.put(s, rs.getInt("c"));
                total += rs.getInt("c");
            }
        }
        return new SystemStats(
                total,
                byStatus.getOrDefault(CandidateStatus.PENDING, 0),
                byStatus.getOrDefault(CandidateStatus.INTERVIEWING, 0),
                byStatus.getOrDefault(CandidateStatus.FINISHED, 0),
                countRows("score"),
                countRows("bonus"));
    }

    // ------------------------------------------------------------------ 四维评分

    ScoreItem insertScore(String studentNo, BigDecimal r, BigDecimal t, BigDecimal s, BigDecimal f,
                          LocalDateTime at) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO score (student_no, r, t, s, f, created_at) VALUES (?, ?, ?, ?, ?, ?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, studentNo);
            ps.setBigDecimal(2, r);
            ps.setBigDecimal(3, t);
            ps.setBigDecimal(4, s);
            ps.setBigDecimal(5, f);
            ps.setTimestamp(6, Timestamp.valueOf(at));
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new ScoreItem(keys.getLong(1), studentNo, r, t, s, f, at);
            }
        }
    }

    List<ScoreItem> listScores(String studentNo) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT id, student_no, r, t, s, f, created_at FROM score WHERE student_no = ? ORDER BY id")) {
            ps.setString(1, studentNo);
            try (ResultSet rs = ps.executeQuery()) {
                List<ScoreItem> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(rowToScore(rs));
                }
                return out;
            }
        }
    }

    Optional<ScoreItem> findScoreByIdAndNo(String studentNo, long id) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT id, student_no, r, t, s, f, created_at FROM score WHERE student_no = ? AND id = ?")) {
            ps.setString(1, studentNo);
            ps.setLong(2, id);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(rowToScore(rs)) : Optional.empty();
            }
        }
    }

    Optional<ScoreItem> lastScore(String studentNo) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT id, student_no, r, t, s, f, created_at FROM score WHERE student_no = ?"
                        + " ORDER BY id DESC LIMIT 1")) {
            ps.setString(1, studentNo);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? Optional.of(rowToScore(rs)) : Optional.empty();
            }
        }
    }

    void deleteScoreByIdAndNo(String studentNo, long id) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "DELETE FROM score WHERE student_no = ? AND id = ?")) {
            ps.setString(1, studentNo);
            ps.setLong(2, id);
            ps.executeUpdate();
        }
    }

    /** 撤销“删除评分”时按日志快照原样恢复（原 id、原四维、原录入时间）。 */
    void restoreScore(long id, String studentNo, BigDecimal r, BigDecimal t, BigDecimal s, BigDecimal f,
                      LocalDateTime at) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO score (id, student_no, r, t, s, f, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)")) {
            ps.setLong(1, id);
            ps.setString(2, studentNo);
            ps.setBigDecimal(3, r);
            ps.setBigDecimal(4, t);
            ps.setBigDecimal(5, s);
            ps.setBigDecimal(6, f);
            ps.setTimestamp(7, Timestamp.valueOf(at));
            ps.executeUpdate();
        }
    }

    // ------------------------------------------------------------------ 附加分

    BonusItem insertBonus(String studentNo, BigDecimal amount, String reason, LocalDateTime at) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO bonus (student_no, amount, reason, created_at) VALUES (?, ?, ?, ?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, studentNo);
            ps.setBigDecimal(2, amount);
            ps.setString(3, reason);
            ps.setTimestamp(4, Timestamp.valueOf(at));
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new BonusItem(keys.getLong(1), studentNo, amount, reason, at);
            }
        }
    }

    List<BonusItem> listBonuses(String studentNo) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT id, student_no, amount, reason, created_at FROM bonus WHERE student_no = ? ORDER BY id")) {
            ps.setString(1, studentNo);
            try (ResultSet rs = ps.executeQuery()) {
                List<BonusItem> out = new ArrayList<>();
                while (rs.next()) {
                    out.add(new BonusItem(rs.getLong("id"), rs.getString("student_no"),
                            rs.getBigDecimal("amount"), rs.getString("reason"),
                            rs.getTimestamp("created_at").toLocalDateTime()));
                }
                return out;
            }
        }
    }

    void deleteBonusByIdAndNo(String studentNo, long id) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "DELETE FROM bonus WHERE student_no = ? AND id = ?")) {
            ps.setString(1, studentNo);
            ps.setLong(2, id);
            ps.executeUpdate();
        }
    }

    // ------------------------------------------------------------------ 操作日志（撤销）

    /**
     * 写一条操作日志。四维评分操作填 r/t/s/f（occurredAt=记录自身录入时间）；
     * 附加分操作填 amount/reason。发生时刻为快照用途。
     */
    void insertOpLog(String studentNo, String opType, long refId,
                     BigDecimal r, BigDecimal t, BigDecimal s, BigDecimal f,
                     BigDecimal amount, String reason, LocalDateTime occurredAt) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO op_log (student_no, op_type, ref_id, r, t, s, f, amount, reason, occurred_at)"
                        + " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")) {
            ps.setString(1, studentNo);
            ps.setString(2, opType);
            ps.setLong(3, refId);
            ps.setBigDecimal(4, r);
            ps.setBigDecimal(5, t);
            ps.setBigDecimal(6, s);
            ps.setBigDecimal(7, f);
            ps.setBigDecimal(8, amount);
            ps.setString(9, reason);
            ps.setTimestamp(10, occurredAt == null ? null : Timestamp.valueOf(occurredAt));
            ps.executeUpdate();
        }
    }

    void deleteOpLogBySeq(long seq) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement("DELETE FROM op_log WHERE seq = ?")) {
            ps.setLong(1, seq);
            ps.executeUpdate();
        }
    }

    Optional<LogRow> lastOpLog() throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement(
                "SELECT o.seq, o.student_no, o.op_type, o.ref_id, o.r, o.t, o.s, o.f, o.amount,"
                        + " o.reason, o.occurred_at, o.created_at,"
                        + " c.name FROM op_log o JOIN candidate c ON c.student_no = o.student_no"
                        + " ORDER BY o.seq DESC LIMIT 1")) {
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    return Optional.empty();
                }
                Timestamp occurred = rs.getTimestamp("occurred_at");
                return Optional.of(new LogRow(
                        rs.getLong("seq"),
                        rs.getString("student_no"),
                        rs.getString("name"),
                        rs.getString("op_type"),
                        rs.getLong("ref_id"),
                        rs.getBigDecimal("r"),
                        rs.getBigDecimal("t"),
                        rs.getBigDecimal("s"),
                        rs.getBigDecimal("f"),
                        rs.getBigDecimal("amount"),
                        rs.getString("reason"),
                        occurred == null ? null : occurred.toLocalDateTime(),
                        rs.getTimestamp("created_at").toLocalDateTime()));
            }
        }
    }

    // ------------------------------------------------------------------ 初始化（保留名单）

    /** 初始化：事务内清空全部四维评分/附加分/操作日志，候选人回到未面试（名单保留）。 */
    void resetAll() throws SQLException {
        boolean oldAuto = conn.getAutoCommit();
        conn.setAutoCommit(false);
        try {
            try (Statement st = conn.createStatement()) {
                st.executeUpdate("DELETE FROM op_log");
                st.executeUpdate("DELETE FROM score");
                st.executeUpdate("DELETE FROM bonus");
                st.executeUpdate("UPDATE candidate SET status = 'PENDING', finished_at = NULL");
            }
            conn.commit();
        } catch (SQLException e) {
            conn.rollback();
            throw e;
        } finally {
            conn.setAutoCommit(oldAuto);
        }
    }

    // ------------------------------------------------------------------ 彻底重置（删除一切数据与库文件）

    /** 彻底重置将删除的目标文件（当前存在的）：库文件与伴生文件 + 数据目录下全部 CSV。 */
    List<String> resetTargets() {
        if (!jdbcUrl.startsWith("jdbc:h2:file:")) {
            throw new IllegalStateException("彻底重置仅支持文件型数据库（jdbc:h2:file:…），当前 URL：" + jdbcUrl);
        }
        String base = jdbcUrl.substring("jdbc:h2:file:".length());
        int semi = base.indexOf(';');
        if (semi >= 0) {
            base = base.substring(0, semi);
        }
        File baseFile = new File(base);
        File dir = baseFile.getAbsoluteFile().getParentFile();
        String fileName = baseFile.getName();
        if (dir == null) {
            throw new IllegalStateException("无法定位数据库文件目录：" + base);
        }
        List<String> targets = new ArrayList<>();
        for (String suffix : new String[]{".mv.db", ".trace.db", ".lock.db"}) {
            File f = new File(dir, fileName + suffix);
            if (f.exists()) {
                targets.add(f.getAbsolutePath());
            }
        }
        File[] csvs = dir.listFiles((d, name) -> name.endsWith(".csv"));
        if (csvs != null) {
            for (File f : csvs) {
                targets.add(f.getAbsolutePath());
            }
        }
        return targets;
    }

    /**
     * 彻底重置：关库 → 删除数据库文件及其伴生文件（*.mv.db / *.trace.db / *.lock.db）与
     * 数据目录下全部 CSV 导出/备份 → 原地重建空库。返回已删除文件列表。
     * 仅支持 {@code jdbc:h2:file:} 文件库。
     */
    List<String> resetEverything() {
        List<String> targets = resetTargets();

        // 1) 关闭连接（H2 文件锁随之释放）
        closeQuietly();
        conn = null;

        // 2) 删除目标文件
        List<String> deleted = new ArrayList<>();
        for (String target : targets) {
            if (new File(target).delete()) {
                deleted.add(target);
            }
        }

        // 3) 重建空库
        try {
            conn = DriverManager.getConnection(jdbcUrl, "sa", "");
            migrationNotice = null;
            initSchema();
        } catch (SQLException e) {
            throw new IllegalStateException("彻底重置后重建数据库失败：" + e.getMessage(), e);
        }
        return deleted;
    }

    private void closeQuietly() {
        if (conn != null) {
            try {
                conn.close();
            } catch (SQLException ignored) {
                // 关闭阶段异常无可控处理点；core 层不允许任何控制台输出
            }
        }
    }

    // ------------------------------------------------------------------ 事务

    /** 在事务中执行动作；成功 commit，异常（SQL/运行时）rollback 后原样抛出。 */
    <T> T tx(TxAction<T> action) throws SQLException {
        boolean oldAuto = conn.getAutoCommit();
        conn.setAutoCommit(false);
        try {
            T result = action.run();
            conn.commit();
            return result;
        } catch (SQLException | RuntimeException e) {
            try {
                conn.rollback();
            } catch (SQLException ignored) {
                // 回滚失败无补救路径，保持原始异常
            }
            throw e;
        } finally {
            conn.setAutoCommit(oldAuto);
        }
    }

    @FunctionalInterface
    interface TxAction<T> {
        T run() throws SQLException;
    }

    // ------------------------------------------------------------------ 杂项

    private int countRows(String table) throws SQLException {
        try (PreparedStatement ps = conn.prepareStatement("SELECT COUNT(*) FROM " + table);
             ResultSet rs = ps.executeQuery()) {
            rs.next();
            return rs.getInt(1);
        }
    }

    private static CandidateInfo rowToCandidate(ResultSet rs) throws SQLException {
        Timestamp finished = rs.getTimestamp("finished_at");
        return new CandidateInfo(
                rs.getString("student_no"),
                rs.getString("name"),
                CandidateStatus.fromDb(rs.getString("status")),
                finished == null ? null : finished.toLocalDateTime());
    }

    private static ScoreItem rowToScore(ResultSet rs) throws SQLException {
        return new ScoreItem(
                rs.getLong("id"),
                rs.getString("student_no"),
                rs.getBigDecimal("r"),
                rs.getBigDecimal("t"),
                rs.getBigDecimal("s"),
                rs.getBigDecimal("f"),
                rs.getTimestamp("created_at").toLocalDateTime());
    }

    private static String escapeLike(String s) {
        return s.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_");
    }

    @Override
    public void close() {
        closeQuietly();
    }

    /** op_log 表原始行（含候选人姓名冗余与四维/附加分快照）。 */
    record LogRow(long seq, String studentNo, String studentName, String opType, long refId,
                  BigDecimal r, BigDecimal t, BigDecimal s, BigDecimal f,
                  BigDecimal amount, String reason,
                  LocalDateTime occurredAt, LocalDateTime time) {
    }
}
